#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Self-host Google Fonts for the CCAF study app (keeps it fully offline).

Fetches the Google Fonts CSS2 stylesheet (with a browser User-Agent so Google
serves modern woff2), downloads only the `latin` subset for each requested
weight into ``study/web/fonts/``, and writes a local ``study/web/fonts.css``
with ``@font-face`` rules pointing at the downloaded files. Re-run to refresh.

Fonts are the property of their authors and are used under their open licenses
(Playfair Display: OFL; Source Sans 3: OFL) — redistribution is permitted.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

__version__ = "1.0.0"

WEB = Path(__file__).resolve().parent.parent / "web"
FONTS_DIR = WEB / "fonts"
FONTS_CSS = WEB / "fonts.css"

# family display name -> weights to fetch
FAMILIES = {
    "Spectral": ["400", "500", "600"],
    "Source Sans 3": ["400", "500", "600", "700"],
}

_BROWSER_UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)


def _slug(family: str) -> str:
    return family.lower().replace(" ", "-")


def build_css2_url() -> str:
    parts = []
    for family, weights in FAMILIES.items():
        fam = family.replace(" ", "+")
        parts.append(f"family={fam}:wght@{';'.join(weights)}")
    return "https://fonts.googleapis.com/css2?" + "&".join(parts) + "&display=swap"


def fetch(url: str, ua: bool = False) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": _BROWSER_UA} if ua else {})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


# Match "/* latin */ @font-face { ... }" blocks (skip latin-ext, cyrillic, etc.)
_BLOCK = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{([^}]*)\}", re.S)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="fetch_fonts.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Download and self-host the study app's Google Fonts (offline).",
        epilog=(
            "Examples:\n"
            "  # Fetch the configured fonts into study/web/fonts/ and write fonts.css:\n"
            "  uv run study/tools/fetch_fonts.py\n\n"
            "  # Print the version:\n"
            "  uv run study/tools/fetch_fonts.py --version\n"
        ),
    )
    p.add_argument("--subset", default="latin", help="Unicode subset to keep (default: latin).")
    p.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    FONTS_DIR.mkdir(parents=True, exist_ok=True)

    for stale in FONTS_DIR.glob("*.woff2"):
        stale.unlink()

    css = fetch(build_css2_url(), ua=True).decode("utf-8")
    # Group by the actual woff2 URL, which makes this robust to BOTH font kinds:
    #  - variable fonts (e.g. Source Sans 3): one URL spans all weights -> one
    #    file + one @font-face with a `font-weight` range;
    #  - static fonts (e.g. Spectral): a distinct URL per weight -> one file and
    #    one @font-face per weight.
    by_url: dict[str, dict] = {}
    for subset, body in _BLOCK.findall(css):
        if subset != args.subset:
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", body)
        wght = re.search(r"font-weight:\s*(\d+)", body)
        url = re.search(r"url\(([^)]+)\)\s*format\('woff2'\)", body)
        if not (fam and wght and url):
            continue
        info = by_url.setdefault(url.group(1), {"family": fam.group(1), "weights": set()})
        info["weights"].add(int(wght.group(1)))

    if not by_url:
        print("ERROR: no font faces found — Google may have changed the CSS format.", file=sys.stderr)
        return 1

    lines = ["/* Self-hosted fonts — generated by tools/fetch_fonts.py. Do not edit by hand. */"]
    for url, info in by_url.items():
        family = info["family"]
        weights = sorted(info["weights"])
        lo, hi = weights[0], weights[-1]
        if lo == hi:
            fname = f"{_slug(family)}-{lo}.woff2"
            weight = str(lo)
        else:
            fname = f"{_slug(family)}.woff2"
            weight = f"{lo} {hi}"
        (FONTS_DIR / fname).write_bytes(fetch(url))
        lines.append(
            f"@font-face{{font-family:'{family}';font-style:normal;font-weight:{weight};"
            f"font-display:swap;src:url('fonts/{fname}') format('woff2');}}"
        )
        print(f"  ↓ {family} (weights {weight})  →  fonts/{fname}")

    FONTS_CSS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {FONTS_CSS.relative_to(WEB.parent)} with {len(by_url)} @font-face rules.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
